[issue-95] enhancement: make start animation value configurable
KoalaPlot/koalaplot-core pull request #98
Opened 2024-12-20 15:24 UTC by OlliZi

Make start animation value configurable.

You can overwrite the default values from PieChart
`labelAnimationSpecStartValue` and
`pieAnimationSpecStartValue` to 1f 

to disable the animation for google sceenshot-testing

2024-12-24 03:24 UTC, gsteckman commented
I suspect that this "bug" in the screenshot testing tool would also impact the rest of the plot types that use animations. It would be good to find a way to factor out the animation aspect to include the ```AnimationSpec```, initial value, and ```LaunchedEffect``` to start the animation so they can be reused in every plot. Do you have any ideas on how to do that? Perhaps a separate class that can be remembered, with a function to start the animation?

2024-12-25 01:03 UTC, gsteckman commented
Yes, that's the direction I was thinking. How about converting the two ```AnimationSpec``` parameters into a single vararg parameter so the class can be used with 1 or more AnimationSpecs? That would also make the ```AnimationSpecs``` class unnecessary.

A second idea is to put the ```Animatable``` values into the class as well and make them public. It would have to be an array to match with the varargs animation specs. Then the start values won't need to be public. When creating the class use a remember, for example
```
remember(values) {
    StartAnimationUseCase(
            executionType = StartAnimationUseCase.ExecutionType.Default,
            chartAnimationSpec = KoalaPlotTheme.animationSpec,
            labelAnimationSpec = tween(LabelFadeInDuration, 0, LinearOutSlowInEasing)
        )
 }
```

with these changes the plot function would only need to invoke ```startAnimationUseCase```. A final optimization would be to add a function in ```StartAnimationUseCase``` to start the animation, e.g., ```fun start(a: Animatable)``` that gets called from the ```LaunchedEffect``` callback. Then the plot doesn't need to be concerned with the target value or the animation spec, and those can be made private within ```StartAnimationUseCase```. This will probably require a map between the ```Animatable``` and the ```AnimationSpec``` so the latter can be looked up when the ```start``` function is called.

2024-12-31 12:23 UTC, OlliZi commented
Ok, thank you:).
I've implemented your feedback. Please take a look:).

The use case is now responsible for 1..n animations and controls them. Now its possible to reuse this use case in other charts.

In my test code i use`ExecutionType.None` to disable the animation for screenshot testing. It works fine:).

2025-01-03 18:31 UTC, OlliZi commented
Do i need add another composable to prevent breaking changes in the API from the PieChart?

2025-01-03 21:51 UTC, gsteckman commented
Hi, thanks for making the change. Yes, it would be good to keep the original function signatures as well, to avoid breaking changes.

2025-01-04 04:25 UTC, gsteckman requested changes
I saw just 1 instance of the original PieChart function that still needs to be preserved.

2025-01-04 04:25 UTC, gsteckman commented on src/commonMain/kotlin/io/github/koalaplot/core/pie/PieChart.kt
> +        ),
The original version of this PieChart overload (which doesn't take a LabelPositionProvider) should also be preserved for API compatibility.

2025-01-04 10:38 UTC, OlliZi commented on src/commonMain/kotlin/io/github/koalaplot/core/pie/PieChart.kt
> +        ),
Done.

2025-01-11 16:42 UTC, gsteckman submitted a review, later dismissed

2025-01-11 17:08 UTC, gsteckman commented
Hi @OlliZi, the build is failing with a couple of detekt violations. Please run gradlew detekt and fix any errors it raises.

2025-01-11 18:51 UTC, OlliZi commented
Done:).

2025-01-11 20:10 UTC, gsteckman approved these changes

2025-01-11 20:10 UTC, merged